---
output: html_document
---

In a simple LLE, the solute partitions itself between an aqueous phase and an organic phase without the complication of other reactions. If the solute is a weak acid, however, then we have to consider both its partition constant, $K_D$, and its acid dissociation constant, $K_a$, when determining its distribution ratio, $D$. The scheme on the bottom right shows the relevant reactions and equations.

The distribution of HA between the two phases is given by the distribution ratio. Solving $K_a$ for $[\text{A}_{aq}^-]$ and substituting into the equation for $D$ gives

$$D = \frac{[\text{HA}_{org}]}{[\text{HA}_{aq}] + \frac{K_a \times [\text{HA}_{aq}]}{[\text{H}_3\text{O}^+]}}$$

Factoring out $[\text{HA}_{aq}]$ and substituting $K_D$ for $[\text{HA}_{org}]/[\text{HA}_{aq}]$ gives

$$D = \frac{K_D[\text{H}_3\text{O}^+]}{[\text{H}_3\text{O}^+] + K_a}$$

Finally the fraction of HA that remains in the aqueous phase is

$$(Q_{aq})_n = \left( \frac{V_{aq}}{D V_{org} + V_{aq}} \right)^n$$

where $n$ is the number of identical extractions. Note that $D$ is a function of $[\text{H}_3\text{O}^+]$, which means $(Q_{aq})_n$ is pH-dependent with the extraction of HA into the organic phase favored when $[\text{H}_3\text{O}^+] >> K_a$ ($\text{pH} << \text{p}K_a$) where the equation for the distribution ratio becomes $D \approx K_D$. Set the sliders on the upper right for $D = 3$, $V_{aq} = V_{org} = 25 \text{ mL}$, $n = 1$, and $\text{p}K_a = 5$ and verify this by adjusting the pH. Compare your results to that for a simple LLE under the same conditions. 
