---
output: html_document
---
Use the controls on the pages for simple LLE, LLE of a Weak Acid, and LLE of a Weak Base to answer the following problems.

Q1. A solute has a distribution ratio between water and hexane of 7.5 . Compare the extraction efficiency if we extract a 50.0-mL portion of an aqueous sample of the solute using 50.0 mL of hexane as a single portion of 50.0 mL, as two portions of 25.0 mL each, as four portions of 12.5 mL each, and as five portions of 10.0 mL each. The solute is neither a weak acid or a weak base.

Q2. A solute has a distribution ratio of 10 between water and hexane. Is it possible to extract 99% of the solute in a 25.0-mL aqueous sample using a single 25.0-mL portion of hexane? If it is not, can you do so by dividing the 25.0 mL of hexane into two or more portions?

Q3. A weak acid, HA, has a p*k~a~* of 5 and a partition constant of 5 between an aqueous phase and an organic phase. What is the greatest extraction efficiency you can achieve using a 25.0-mL portion of the weak acid and a 25.0-mL portion of the organic phase? Suppose you want to minimize the extraction of HA, what limitation can you place on the sample's pH such that less than 1% of HA is extracted into the organic phase. Assume equal volumes of the weak acid and the organic phase.

The following two problems use the schemes on the right.

Q4. The relevant reactions for the extraction of iodine, I~2~, from an aqueous solution of KI into an organic phase are shown on the upper right. Predict whether the extraction efficiency for I~2~ increases or decreases for higher concentrations of I6^--^. Derive an equation for the distribution ratio and the extraction efficiency for this system.

Q5. The relevant reactions for the extraction of the metal-ligand complex ML~2~ from an aqueous solution into an organic phase are shown on the lower right. Predict whether the extraction efficiency for ML~2~ increases or decreases with an increase in the ligand's concentration. Derive and equation for the distribution ratio and the extraction efficiency for this system.
