---
output: html_document
---

In a simple liquid--liquid extraction (LLE) a solute, S, partitions itself between two immiscible phases, one aqueous and one organic. The scheme on the bottom right shows this as an equilibrium reaction with a distribution ratio, $D$, for the solute that is equivalent to its equilibrium partition constant, $K_D$.

If the solute begins in the aqueous phase, then a conservation of mass requires that the moles of S in the aqueous phase before the extraction is equal to the moles of S in both phases after the extraction

$$(\text{mol S}_{aq})_0 = (\text{mol S}_{aq})_1 + (\text{mol S}_{org})_1$$

Solving for $(\text{mol S}_{org})_1$, substituting into the equation for $D$ and rearranging gives

$$D = \frac{\frac{(\text{mol S}_{aq})_0 - (\text{mol S}_{aq})_1}{V_{org}}}{\frac{(\text{mol S}_{aq})_1}{V_{aq}}} = \frac{(\text{mol S}_{aq})_0 \times V_{aq} - (\text{mol S}_{aq})_1 \times V_{aq}}{(\text{mol S}_{aq})_1 \times V_{org}}$$

$$Q_{aq} = \frac{(\text{mol S}_{aq})_1}{(\text{mol S}_{aq})_0} = \frac{V_{aq}}{D V_{org} + V_{aq}}$$

where $Q_{aq}$ is the fraction of solute that remains in the aqueous phase after the extraction. For *n* identical extractions, the fraction that remains in the aqueous phase, $(Q_{aq})_n$, is

$$(Q_{aq})_n = \left( \frac{V_{aq}}{D V_{org} + V_{aq}} \right)^n$$

Use the sliders and table on the upper right to verify that $V_{aq} >> D V_{org}$ and a smaller *n* favors retaining the solute in the aqueous phase, and that $V_{aq} << D V_{org}$ and a larger *n* favors moving the solute into the organic phase.
